# Generated by Django 6.0.3 on 2026-04-07 13:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de item',
                'verbose_name_plural': 'Categorias de itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao_padrao', models.TextField(blank=True)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('hr', 'Hora'), ('dia', 'Diária'), ('m', 'Metro'), ('m2', 'Metro quadrado'), ('m3', 'Metro cúbico'), ('kg', 'Quilo'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('sv', 'Serviço')], default='un', max_length=10)),
                ('valor_unitario_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='catalogo.categoriaitem')),
            ],
            options={
                'verbose_name': 'Item de catálogo',
                'verbose_name_plural': 'Itens de catálogo',
                'ordering': ['nome'],
            },
        ),
    ]
