# Generated by Django 6.0.3 on 2026-04-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogo', '0002_categoriaitem_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaitem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_catalogo', to='auth.group'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_catalogo', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='categoriaitem',
            name='cor',
            field=models.CharField(choices=[('#2563EB', 'Azul'), ('#DC2626', 'Vermelho'), ('#EAB308', 'Amarelo'), ('#16A34A', 'Verde'), ('#EA580C', 'Laranja'), ('#7C3AED', 'Roxo'), ('#DB2777', 'Rosa'), ('#92400E', 'Marrom'), ('#111827', 'Preto'), ('#FFFFFF', 'Branco')], default='#2563EB', max_length=7),
        ),
        migrations.AlterField(
            model_name='categoriaitem',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemcatalogo',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='categoriaitem',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='categoriaitem_empresa_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemcatalogo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='itemcatalogo_empresa_codigo_uniq'),
        ),
    ]
