# Generated by Django 6.0.3 on 2026-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_substituir_cor_branca_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaitem',
            name='cor',
            field=models.CharField(choices=[('#2563EB', 'Azul'), ('#DC2626', 'Vermelho'), ('#EAB308', 'Amarelo'), ('#16A34A', 'Verde'), ('#EA580C', 'Laranja'), ('#7C3AED', 'Roxo'), ('#DB2777', 'Rosa'), ('#92400E', 'Marrom'), ('#111827', 'Preto'), ('#475569', 'Grafite')], default='#2563EB', max_length=7),
        ),
        migrations.AlterField(
            model_name='itemcatalogo',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('hr', 'Hora'), ('dia', 'Diária'), ('m', 'm'), ('m2', 'm2'), ('m3', 'm3'), ('kg', 'Quilo'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('sv', 'Serviço'), ('-', '-')], default='un', max_length=10),
        ),
    ]
