# Generated by Django 6.0.3 on 2026-07-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_categoriaitem_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaitem',
            name='cor',
            field=models.CharField(choices=[('#17795A', 'Verde-tinta'), ('#2563EB', 'Azul'), ('#DC2626', 'Vermelho'), ('#EAB308', 'Amarelo'), ('#16A34A', 'Verde'), ('#EA580C', 'Laranja'), ('#7C3AED', 'Roxo'), ('#DB2777', 'Rosa'), ('#92400E', 'Marrom'), ('#111827', 'Preto'), ('#475569', 'Grafite')], default='#17795A', max_length=7),
        ),
    ]
