# Generated by Django 6.0.3 on 2026-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_configuracaoempresa_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='assinatura_cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='assinatura_contato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='assinatura_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='dados_bancarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='texto_institucional_memorial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='validade_padrao_proposta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
