# Generated by Django 6.0.3 on 2026-04-12

from django.db import migrations, models
import django.db.models.deletion


def bootstrap_empresas(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Empresa = apps.get_model("core", "Empresa")
    for grupo in Group.objects.all():
        Empresa.objects.get_or_create(
            grupo=grupo,
            defaults={"nome": grupo.name, "ativa": True},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "grupo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresa_registro",
                        to="auth.group",
                    ),
                ),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.RunPython(bootstrap_empresas, migrations.RunPython.noop),
    ]
