# Generated by Django 6.0.3 on 2026-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('hr', 'Hora'), ('dia', 'Diária'), ('m', 'Metro'), ('m2', 'Metro quadrado'), ('m3', 'Metro cúbico'), ('kg', 'Quilo'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('sv', 'Serviço')], default='un', max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='mostrar_ajustes_no_relatorio',
            field=models.BooleanField(default=False, help_text='Se marcado, o relatório do cliente mostra descontos e acréscimos detalhados.'),
        ),
    ]
