# Generated by Django 6.0.3 on 2026-04-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientes', '0002_cliente_empresa'),
        ('orcamentos', '0003_orcamento_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='numero',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='orcamento_empresa_numero_uniq'),
        ),
    ]
