# Generated by Django 6.0.3 on 2026-04-10 13:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_orcamento_empresa_alter_orcamento_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='condicoes_pagamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_cargo_funcao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_inscricao_estadual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_responsavel_documento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_responsavel_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='contrato_telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_contato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_estande',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_local',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_periodo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento_telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='servicos_taxas_inclusos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_locacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_servico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
