# Generated by Django 6.0.3 on 2026-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0005_orcamento_condicoes_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_contatos_evento_no_memorial",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o memorial inclui os contatos do evento ou projeto.",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_dados_contratuais_no_memorial",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o memorial inclui os dados contratuais.",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_descricao_inicial_no_relatorio",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o PDF do orçamento inclui a descrição inicial.",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_financeiro_no_memorial",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o memorial inclui condições financeiras e dados bancários.",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_informacoes_complementares_no_memorial",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o memorial inclui textos institucionais complementares.",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_observacoes_gerais_no_relatorio",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o PDF e o memorial incluem as observações gerais.",
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="mostrar_rodape_institucional_no_relatorio",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, o PDF do orçamento inclui o rodapé institucional da empresa.",
            ),
        ),
    ]
