# Generated by Django 6.0.3 on 2026-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_orcamento_opcoes_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('hr', 'Hora'), ('dia', 'Diária'), ('m', 'm'), ('m2', 'm2'), ('m3', 'm3'), ('kg', 'Quilo'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('sv', 'Serviço'), ('-', '-')], default='un', max_length=10),
        ),
    ]
