# Generated by Django 6.0.3 on 2026-04-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0004_configuracaoempresa_assinatura_cargo_and_more"),
        ("orcamentos", "0007_alter_itemorcamento_unidade_medida"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="configuracao_empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orcamentos",
                to="relatorios.configuracaoempresa",
            ),
        ),
    ]
